# Generated by Django 4.2.5 on 2024-07-05 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaigns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('schedule_at', models.DateTimeField()),
                ('campaign_name', models.CharField(default='', max_length=50)),
                ('domain_name', models.CharField(default='', max_length=50)),
                ('urls', models.TextField(default='')),
                ('keywords', models.TextField(default='')),
                ('search_engines', models.CharField(choices=[('Google', 'Google')], default='Google', max_length=100)),
                ('repetition_count', models.PositiveIntegerField(default=1)),
                ('visit_count_from', models.PositiveIntegerField(default=1)),
                ('visit_count_to', models.PositiveIntegerField(default=1)),
                ('count', models.PositiveIntegerField(default=3)),
                ('from_time', models.PositiveIntegerField(default=1)),
                ('to_time', models.PositiveIntegerField(default=3)),
                ('scroll_duration', models.PositiveIntegerField(default=30)),
                ('proxy_file', models.FileField(upload_to='proxies/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
    ]
