# Generated by Django 4.2.5 on 2024-07-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_tasks_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cookies/')),
            ],
            options={
                'verbose_name': 'Cookie File',
                'verbose_name_plural': 'Cookie Files',
            },
        ),
        migrations.AddField(
            model_name='campaigns',
            name='cookie_files',
            field=models.ManyToManyField(blank=True, related_name='campaigns', to='dashboard.cookiefile'),
        ),
    ]
