# Generated by Django 4.2.5 on 2024-07-06 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_cookiefile_campaigns_cookie_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigns',
            name='cookie_files',
        ),
        migrations.AddField(
            model_name='cookiefile',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cookie_files', to='dashboard.campaigns'),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='search_engines',
            field=models.CharField(choices=[('Google', 'Google'), ('Bing', 'Bing'), ('Yahoo', 'Yahoo')], default='Google', max_length=100),
        ),
    ]
