# Generated by Django 4.2.5 on 2024-07-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_campaigns_cookie_files_cookiefile_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='facebook_urls',
            field=models.TextField(default=''),
        ),
    ]
