# Generated by Django 4.2.5 on 2024-07-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_campaigns_facebook_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='facebook_urls',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
