# Generated by Django 4.2.5 on 2024-07-06 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_campaigns_facebook_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='time_zone',
            field=models.CharField(default='America/New_York', max_length=50),
        ),
    ]
