# Generated by Django 4.2.5 on 2024-07-11 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_chrome_versions_campaigns_executable_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigns',
            name='executable_path',
        ),
        migrations.RemoveField(
            model_name='campaigns',
            name='user_Data_Dir',
        ),
        migrations.AddField(
            model_name='campaigns',
            name='extension_path',
            field=models.CharField(default='C:/Users/atulg/Desktop/WebRTC-Leak-Prevent', max_length=100),
        ),
    ]
