# Generated by Django 4.2.5 on 2024-07-11 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_remove_campaigns_executable_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='cookies_file',
            field=models.FileField(blank=True, null=True, upload_to='cookies_zip/'),
        ),
        migrations.CreateModel(
            name='Cookies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_data', models.JSONField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.campaigns')),
            ],
        ),
    ]
