# Generated by Django 4.2.5 on 2024-07-12 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_cookies_options_remove_campaigns_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cookiefile',
            options={'verbose_name': 'Cookie Upload', 'verbose_name_plural': 'Cookies Upload'},
        ),
        migrations.CreateModel(
            name='Proxyfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='proxies/')),
                ('campaign', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proxyfile', to='dashboard.campaigns')),
            ],
            options={
                'verbose_name': 'Proxy Upload',
                'verbose_name_plural': 'Proxies Upload',
            },
        ),
    ]
