# Generated by Django 4.2.5 on 2024-07-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_alter_cookiefile_options_proxyfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyfile',
            name='proxies',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
