# Generated by Django 4.2.5 on 2024-07-12 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_proxyfile_proxies'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgentsFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agents', models.TextField(blank=True, default='', null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='useragents/')),
                ('Chrome_version', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chromeversions', to='dashboard.chrome_versions')),
            ],
            options={
                'verbose_name': 'User Agents Upload',
                'verbose_name_plural': 'User Agents Upload',
            },
        ),
    ]
