# Generated by Django 4.2.5 on 2024-07-12 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_alter_campaigns_extension_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigns',
            name='facebook_urls',
        ),
    ]
