# Generated by Django 4.2.5 on 2024-07-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_alter_campaigns_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='facebook_campaign',
            field=models.BooleanField(default=False),
        ),
    ]
