# Generated by Django 4.2.5 on 2024-07-16 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_remove_campaigns_search_engines_searchengine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_agents',
            name='height',
            field=models.PositiveIntegerField(default=864),
        ),
        migrations.AddField(
            model_name='user_agents',
            name='isMobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_agents',
            name='width',
            field=models.PositiveIntegerField(default=1536),
        ),
    ]
