# Generated by Django 5.0.3 on 2024-08-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_user_agents_height_user_agents_ismobile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='profile_delay',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
