# Generated by Django 5.0.3 on 2024-08-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_tasks_profile_delay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='count',
        ),
        migrations.AddField(
            model_name='tasks',
            name='profile',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
