# Generated by Django 5.0.3 on 2024-08-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_remove_tasks_count_tasks_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaigns',
            old_name='scroll_duration',
            new_name='scroll_duration_to',
        ),
        migrations.AddField(
            model_name='campaigns',
            name='scroll_duration_from',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
