# Generated by Django 5.0.3 on 2024-08-29 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_alter_campaigns_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='only_last_page_scroll_for_facebook',
            field=models.BooleanField(default=False),
        ),
    ]
