# Generated by Django 5.0.3 on 2024-08-29 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_campaigns_only_last_page_scroll_for_facebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='profile_delay',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
