# Generated by Django 5.0.3 on 2024-08-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_proxy_city_proxy_country_proxy_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='status',
            field=models.CharField(choices=[('FETCHING', 'FETCHING'), ('BAD', 'BAD'), ('GOOD', 'GOOD')], default='FETCHING', max_length=100),
        ),
    ]
