# Generated by Django 5.0.3 on 2024-08-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_alter_campaigns_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigns',
            name='country',
        ),
        migrations.AddField(
            model_name='campaigns',
            name='continent',
            field=models.CharField(blank=True, choices=[('Africa', 'Africa'), ('Antarctica', 'Antarctica'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('Oceania', 'Oceania'), ('South America', 'South America')], max_length=100, null=True),
        ),
    ]
