# Generated by Django 5.0.3 on 2024-08-30 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0036_remove_campaigns_country_campaigns_continent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBehaviour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scroll_duration_from', models.PositiveIntegerField(default=10)),
                ('scroll_duration_to', models.PositiveIntegerField(default=30)),
            ],
            options={
                'verbose_name': 'Page Behaviour',
                'verbose_name_plural': 'Pages Behaviours',
            },
        ),
        migrations.RemoveField(
            model_name='campaigns',
            name='scroll_duration_from',
        ),
        migrations.RemoveField(
            model_name='campaigns',
            name='scroll_duration_to',
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='proxy_file',
            field=models.FileField(blank=True, null=True, upload_to='proxies/'),
        ),
        migrations.CreateModel(
            name='CampaignPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.campaigns')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.pagebehaviour')),
            ],
            options={
                'ordering': ['sequence'],
                'unique_together': {('campaign', 'sequence')},
            },
        ),
        migrations.AddField(
            model_name='campaigns',
            name='pages',
            field=models.ManyToManyField(through='dashboard.CampaignPage', to='dashboard.pagebehaviour'),
        ),
    ]
