# Generated by Django 5.0.3 on 2024-08-30 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0038_campaigns_direct_traffic'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='facebook_post_div',
            field=models.CharField(default='div.x11i5rnm.xat24cr.x1mh8g0r.x1vvkbs.xtlvy1s.x126k92a', max_length=200),
        ),
    ]
