# Generated by Django 5.0.3 on 2024-09-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0039_campaigns_facebook_post_div'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='facebook_ads_div',
            field=models.CharField(default='div.search__result__wrapper', max_length=200),
        ),
    ]
