# Generated by Django 5.0.3 on 2024-09-09 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_campaigns_facebook_ads_div'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proxy',
            name='city',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='country',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='region',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='status',
        ),
        migrations.RemoveField(
            model_name='proxy',
            name='timezone',
        ),
    ]
