# Generated by Django 5.0.3 on 2024-09-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_remove_proxy_city_remove_proxy_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='proxy',
            name='status',
            field=models.CharField(choices=[('FETCHING', 'FETCHING'), ('BAD', 'BAD'), ('GOOD', 'GOOD')], default='FETCHING', max_length=100),
        ),
        migrations.AddField(
            model_name='proxy',
            name='timezone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
