# Generated by Django 5.0.3 on 2024-09-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_remove_campaigns_continent_campaigns_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='time_zone',
            field=models.CharField(max_length=50000),
        ),
    ]
