# Generated by Django 5.0.3 on 2024-09-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0045_remove_campaigns_country_campaigns_continent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigns',
            name='only_last_page_scroll_for_facebook',
        ),
        migrations.AddField(
            model_name='campaigns',
            name='direct_urls',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='selection_on_page',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='keywords',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='campaigns',
            name='urls',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
