# Generated by Django 5.0.3 on 2024-09-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0046_remove_campaigns_only_last_page_scroll_for_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cookies',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='campaigns',
            name='cookies_file',
        ),
        migrations.AddField(
            model_name='campaigns',
            name='cookies_folder',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='CookieFile',
        ),
        migrations.DeleteModel(
            name='Cookies',
        ),
    ]
