# Generated by Django 5.0.3 on 2024-09-12 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_remove_cookies_campaign_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='click_anywhere',
            field=models.BooleanField(default=False),
        ),
    ]
