# Generated by Django 5.0.3 on 2024-09-12 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0048_campaigns_click_anywhere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaigns',
            name='extension_path',
        ),
    ]
