# Generated by Django 5.0.3 on 2024-09-12 08:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0049_remove_campaigns_extension_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='schedule_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
