# Generated by Django 5.0.3 on 2024-09-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0050_alter_tasks_schedule_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaigns',
            name='cookies_folder',
            field=models.CharField(default='Empty', max_length=50),
        ),
    ]
