# Generated by Django 5.0.3 on 2024-09-13 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0053_campaigns_is_iframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagebehaviour',
            name='click_selector',
            field=models.CharField(default='a', max_length=500),
        ),
    ]
