# Generated by Django 5.0.3 on 2024-09-13 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0054_pagebehaviour_click_selector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagebehaviour',
            name='click_selector',
            field=models.CharField(default='body', max_length=500),
        ),
    ]
