# Generated by Django 5.0.3 on 2024-09-18 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_pagebehaviour_is_iframe'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='campaignpage',
            unique_together=set(),
        ),
    ]
