# Generated by Django 5.1.1 on 2024-09-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0058_campaigns_main_proxy_campaigns_session_string_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxy',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
