# Generated by Django 5.1.1 on 2024-09-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0059_proxy_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_agents',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AddField(
            model_name='user_agents',
            name='WebGL',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='user_agents',
            name='WebGL_report',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='user_agents',
            name='audio',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='user_agents',
            name='canvas',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='user_agents',
            name='client_rects',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='user_agents',
            name='color_depth',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='user_agents',
            name='device_memory',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='user_agents',
            name='hardware_concurrency',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='user_agents',
            name='screen_resolution',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='user_agents',
            name='touch_support',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='user_agents',
            name='unmasked_renderer',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='user_agents',
            name='unmasked_vendor',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='user_agents',
            name='visitor_id',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='user_agents',
            name='webGPU_report',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='user_agents',
            name='user_agent',
            field=models.CharField(default='', max_length=400),
        ),
    ]
