# Generated by Django 4.2.7 on 2024-09-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0062_alter_campaigns_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaigns',
            name='profiles_tag',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='campaigns',
            name='use_login_profiles',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tasks',
            name='make_google_logins',
            field=models.BooleanField(default=False),
        ),
    ]
