# Generated by Django 4.2.7 on 2024-09-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0064_tasks_youtube_subscribe_tasks_youtube_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='create_google_accounts',
            field=models.BooleanField(default=False),
        ),
    ]
